spring:

  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hyeding1
    username: sa
    password: 1

  data:
    web:
      pageable:
        default-page-size: 20  #페이징 할 때 기본값, 20개씩 조회

  servlet:
    multipart:
      max-request-size: 5MB  #업로드 파일 크기 총량 제한
      max-file-size: 2MB     #업로드 파일 크기 제한

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true

        default_batch_fetch_size: 100 #배치 사이즈 (Collection 조회 최적화)

    hibernate:
      ddl-auto: none

    open-in-view: false #OSIV 사용하지 않기

  cache:
    redis:
      time-to-live: 86400000 #mills 단위 -> [1초 : 1000] ->   [1일 : 86400000]

  redis:
    port: 6379
    host: 127.0.0.1

#Log
logging:
  level:
    p6spy: debug

    org:
      apache:
        coyote:
          http11: debug #debug

      hiberante:
        SQL: debug

    boardexample:
      myboard: debug


file:
  dir: D:\files\